/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://t4pymm2zujguzddqz3z7xhnpnm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ub5izryzxfdbfllb376ov56hmi",
    "aws_cognito_identity_pool_id": "us-west-2:a21f2e78-c87d-4ceb-b31c-4aa3e1d38df4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_GwCUsboJq",
    "aws_user_pools_web_client_id": "37o4pmtvjmlnf26kqciumko3ll",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "trainrspace9789522308584244a44e0900562a1668134707-backdev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
